// <auto-generated />
using System;
using GameCollection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameCollection.Migrations
{
    [DbContext(typeof(GameCollectionDbContext))]
    partial class GameCollectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameCollection.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 3,
                            Platform = "PC",
                            Rating = 10,
                            ReleaseYear = 2015,
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 1,
                            Platform = "PlayStation 5",
                            Rating = 9,
                            ReleaseYear = 2022,
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 6,
                            Platform = "PC",
                            Rating = 9,
                            ReleaseYear = 2016,
                            Title = "Stardew Valley"
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 4,
                            Platform = "PlayStation 5",
                            Rating = 7,
                            ReleaseYear = 2023,
                            Title = "FIFA 24"
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 5,
                            Platform = "PC",
                            Rating = 8,
                            ReleaseYear = 2016,
                            Title = "Civilization VI"
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 7,
                            Platform = "PlayStation 5",
                            Rating = 8,
                            ReleaseYear = 2021,
                            Title = "Resident Evil Village"
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 2,
                            Platform = "Nintendo Switch",
                            Rating = 10,
                            ReleaseYear = 2017,
                            Title = "Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 1,
                            Platform = "Xbox Series X",
                            Rating = 8,
                            ReleaseYear = 2021,
                            Title = "Halo Infinite"
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 5,
                            Platform = "Mobile",
                            Rating = 7,
                            ReleaseYear = 2018,
                            Title = "Among Us"
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 1,
                            Platform = "PlayStation 4",
                            Rating = 10,
                            ReleaseYear = 2018,
                            Title = "God of War"
                        });
                });

            modelBuilder.Entity("GameCollection.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("GameCollection.Models.Game", b =>
                {
                    b.HasOne("GameCollection.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
